language: node_js

node_js:
  - "11"

os:
  - linux

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: lint
      script:
        - ng lint
    - stage: test
      script:
        - npm run test:lib-coverage
        - npm run report-coverage:lib
    - stage: build and publish demo
      script:
        - npm run build:demo
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: dist/data-grid-demo
    - stage: build lib
      script:
        - npm run build:lib
