sudo: required

language: node_js

node_js:
  - "11"

dist: trusty

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

jobs:
  include:
    - stage: lint and test
      script:
        - ng lint
        - npm run test:lib-coverage
        - npm run report-coverage:lib
    - stage: build and publish
      script:
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: dist/data-grid-demo
        on:
          branch: develop

notifications:
  email: false
