# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NgRxDataGrid CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: install dependencies
        - run: npm ci
      
    - name: lint and test
        - run: npm run lint
        - run: npm run test:lib-coverage
        - run: npm run report-coverage:lib
        
    - name: build
        - run: npm run build
